name: Dependency review

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: dependency-review-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    uses: abijith-suresh/workflows/.github/workflows/dependency-review.yml@e59572c426373f5864ef1a6dad2524b47280a30c # Release Please v0.4.1
    with:
      fail-on-severity: high
    permissions:
      contents: read
