name: Dependency review

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: dependency-review-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    uses: abijith-suresh/workflows/.github/workflows/dependency-review.yml@a53b4c876bca362ca058c99c01c4c0a955d71c9d # 0.7.0
    with:
      fail-on-severity: high
    permissions:
      contents: read
