name: Dependency review

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: dependency-review-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    uses: abijith-suresh/workflows/.github/workflows/dependency-review.yml@163055ac24b4169ae93ae05c5d7491b1cd5d96c7 # Release Please v0.6.0
    with:
      fail-on-severity: high
    permissions:
      contents: read
