name: PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  pr-title:
    name: pr-title
    uses: abijith-suresh/workflows/.github/workflows/conventional-commit-title.yml@a53b4c876bca362ca058c99c01c4c0a955d71c9d # 0.7.0
    permissions:
      pull-requests: read
